### ISSUE TITLE
Compose hook

### ISSUE THREAD

**Issue by gchaincl** [gchaincl/sqlhooks#12]
In order to combine multiple hooks (log+tracing) a new (compose) hook can be implemented. It should accept a list of Hooks and chain them together.

**Comment by keegancsmith** [comment]
You can just compose the wrapped drivers. However, that does have a higher performance penalty.

**Comment by gchaincl** [comment]
You're right, that's why a composer hook sounds more convenient.
I'm thinking about something like:
```golang
hooks := ComposeHooks(&HooksA{}, &HooksB{})
sql.Register("sqlite3WithHooks", sqlhooks.Wrap(&sqlite3.SQLiteDriver{}, hooks))
```

**Comment by keegancsmith** [comment]
SGTM and should be easy to implement. I'd suggest calling it `Compose` to avoid the stutter with the package name (ie users will be doing `sqlhooks.ComposeHooks` vs `sqlhooks.Compose`). I actually used this recently to compose my OT hook with the logger hook to try debug stuff.

**Comment by ccmtaylor** [comment]
I'll take a stab at this if you don't mind.
