### ISSUE TITLE
Tag latest commit

### ISSUE THREAD

**Issue by keegancsmith** [gchaincl/sqlhooks#16]
There have been a few changes to sqlhooks. We should probably tag the latest commit. I noticed this while trying out the dep tool.

**Comment by keegancsmith** [comment]
Agreed. I gave it a review and had a few review comments.

**Comment by gchaincl** [comment]
I'm closing this since [`v.1.2.0`](https://github.com/gchaincl/sqlhooks/tree/v1.2.0) has been released
