### ISSUE TITLE
Include Go version requirement in README

### ISSUE THREAD

**Issue by tcprbs** [gchaincl/sqlhooks#17]
The latest version has implemented some new interfaces defined in Go 1.8. It would be useful if the Go version required is mentioned in the README.

**Comment by gchaincl** [comment]
you are right, thanks for noticing that @tcprbs, do you want to give it a try?

**Comment by tcprbs** [comment]
@gchaincl Done. Raised a [PR](https://github.com/gchaincl/sqlhooks/pull/18) here.

**Comment by keegancsmith** [comment]
Fixed by https://github.com/gchaincl/sqlhooks/pull/18
