### ISSUE TITLE
Implement new 1.8 interfaces

### ISSUE THREAD

**Issue by luna-duclos** [gchaincl/sqlhooks#3]
Go 1.8 has added a bunch of new interfaces that need to be wrapped, all the context related functions pretty much.

**Comment by gchaincl** [comment]
You're right, great point.

**Comment by gchaincl** [comment]
After reading database/sql implementation, I've realized that:
`Query("SELECT * FROM TABLE")` calls `QueryContext(context.Background(), "SELECT * FROM TABLE")`. So effectively, by hooking to the Driver's `Query` implementation will work for both cases.

**Comment by gchaincl** [comment]
done in #5
