### ISSUE TITLE
how to log sql when sql execute failed?

### ISSUE THREAD

**Issue by song-without-words** [gchaincl/sqlhooks#32]

**Comment by gchaincl** [comment]
Did you try implementing the on `OnErrorer`[1] interface?
[1]: https://github.com/gchaincl/sqlhooks/blob/master/sqlhooks.go#L21

**Comment by song-without-words** [comment]
thanks for your response. it worked!

**Comment by song-without-words** [comment]
Sorry, now i have a new problem. Sometimes error log will print twice and i can't find the reason.

**Comment by gchaincl** [comment]
can u send the code

**Comment by song-without-words** [comment]
`
func (h *Hooks) OnError(ctx context.Context, err error, query string, args ...interface{}) error {
	begin := ctx.Value("begin").(time.Time)
	var traceLog string
	res := ctx.Value("traceLog")
	if res != nil {
		traceLog = res.(string)
	} else {
		traceLog, _ = shortid.Generate()
	}
	l := clog.NewWithCtx(traceLog)
	l.Info("SQL | %10s | %s %v", utils.FormatDuration(time.Since(begin)), query, args)
	return err
}
` then sometimes error sql will log  twice.

**Comment by song-without-words** [comment]
`
func (h *Hooks) OnError(ctx context.Context, err error, query string, args ...interface{}) error {
	begin := ctx.Value("begin").(time.Time)
	var traceLog string
	res := ctx.Value("traceLog")
	if res != nil {
		traceLog = res.(string)
	} else {
		traceLog, _ = shortid.Generate()
	}
	l := clog.NewWithCtx(traceLog)
	l.Info("SQL | %10s | %s %v", utils.FormatDuration(time.Since(begin)), query, args)
	return err
}
`
then sometimes error sql will log twice.

**Comment by song-without-words** [comment]
`
func (h *Hooks) OnError(ctx context.Context, err error, query string, args ...interface{}) error {\n
	begin := ctx.Value("begin").(time.Time)\n
	var traceLog string\n
	res := ctx.Value("traceLog")\n
	if res != nil {\n
		traceLog = res.(string)\n
	} else {\n
		traceLog, _ = shortid.Generate()\n
	}\n
	l := clog.NewWithCtx(traceLog)\n
	l.Info("SQL | %10s | %s %v", utils.FormatDuration(time.Since(begin)), query, args)\n
	return err\n
}\n
`
then error sql will log twice.

**Comment by song-without-words** [comment]
func (h *Hooks) OnError(ctx context.Context, err error, query string, args ...interface{}) error {

	begin := ctx.Value("begin").(time.Time)
	var traceLog string
	res := ctx.Value("traceLog")
	if res != nil {
		traceLog = res.(string)
	} else {
		traceLog, _ = shortid.Generate()
	}
	l := clog.NewWithCtx(traceLog)
	l.Info("SQL | %10s | %s %v", utils.FormatDuration(time.Since(begin)), query, args)
	return err
    }


then error sql will log twice.

**Comment by gchaincl** [comment]
could you just try to print a single like in the `OnError` hook?
so that we can be sure that the problem is with the hook and not with your logger?

**Comment by song-without-words** [comment]
thanks for your response.  now i think the problem is not with the hook.  i use sqlx, then whatever sql is right or wrong, sqlx throws a driver.ErrSkip error and OnError func will exec, so if sql is right, it will print twice.Do you know how to solve it？
` error: driver: skip fast-path; continue as if unimplemented`

**Comment by gchaincl** [comment]
can you `fmt.Printf("error: %+v (%T)", err, err)` on the hook.
If the errors are different you can act differently depending on the error you get

**Comment by song-without-words** [comment]
thanks for your response, but unfortunately, the errors is the same.
`error: driver: skip fast-path; continue as if unimplemented (*errors.errorString)`
